/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Nov 19, 2015
 *			
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"      SUMMARY OF THE HDF5 CONFIGURATION\n"
	"      =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.8.16\n"
	"                  Configured on: 2015-11-19\n"
	"                  Configured by: Visual Studio 12 2013 Win64\n"
	"                 Configure mode: CMAKE 3.3.0\n"
	"                    Host system: Windows-6.1\n"
	"              Uname information: Windows\n"
	"                       Byte sex: little-endian\n"
	"                      Libraries: \n"
	"             Installation point: C:/Program Files/HDF_Group/HDF5/1.8.16\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: \n"
	"                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe\n"
	"                         CFLAGS:  /DWIN32 /D_WINDOWS /W3 /O3 /xHost /ip\n"
	"                      H5_CFLAGS: \n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"               Shared C Library: YES\n"
	"               Static C Library: YES\n"
	"  Statically Linked Executables: OFF\n"
	"                        LDFLAGS:  /machine:x64\n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: \n"
	"                       Archiver: \n"
	"                         Ranlib: \n"
	"              Debugged Packages: \n"
	"                    API Tracing: OFF\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.0.110/windows/bin/intel64_mic/ifort.exe\n"
	"          Fortran 2003 Compiler: \n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"         Shared Fortran Library: YES\n"
	"         Static Fortran Library: YES\n"
	"\n"
	"                            C++: ON\n"
	"                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe\n"
	"                      C++ Flags:  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /O3 /xHost /ip\n"
	"                   H5 C++ Flags: \n"
	"                   AM C++ Flags: \n"
	"             Shared C++ Library: YES\n"
	"             Static C++ Library: YES\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: OFF\n"
	"             High Level library: ON\n"
	"                   Threadsafety: OFF\n"
	"            Default API Mapping: v18\n"
	" With Deprecated Public Symbols: ON\n"
	"         I/O filters (external): \n"
	"                            MPE: \n"
	"                     Direct VFD: \n"
	"                        dmalloc: \n"
	"Clear file buffers before write: ON\n"
	"           Using memory checker: OFF\n"
	"         Function Stack Tracing: OFF\n"
	"      Strict File Format Checks: OFF\n"
	"   Optimization Instrumentation: \n"
;

